spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

page-size-for-invitations: 10
page-size: 10