version: '3.9'
name: cupid-link
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cupid-link
    ports:
      - '5432:5432'
