spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
page-size-for-invitations: 10
page-size: 10