spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queue: cupid-link
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
page-size-for-invitations: 10
page-size: 10
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

jackson:
  serialization:
    fail-on-empty-beans: false