spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queue: cupid-link

page-size-for-invitations: 10
page-size: 10